# numpy 실습


In [2]:
import numpy as np

In [6]:
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
             [10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#reshape(x,y) -> x,y는 전체 요소의 개수의 약수의 형태여야 한다.
print("a shape = {}".format(a.shape))
b = a.reshape(6,2)
print(b)

print()
#-1로 한쪽만 지정할 수 있음
print(a.reshape(3,-1))

a shape = (4, 3)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 배열 인덱싱&슬라이싱

In [36]:
#a[행,열] -> 행은 생략 불가(:처리), 열은 생략 가능

#인덱싱
print(a)
print()
print(a[2]) # [값, 범위] -> 1차원
print()
print(a[:,2]) # [범위, 값] -> 1차원
print()
print(a[:,[2]]) # [범위, 범위] ->2차원
print()
print(a[[2]]) # [범위, 범위] ->2차원 (생략도 :라는 범위니까!)
print()
print(a[[0,1]])
print()
print(a[[0],[1,2]]) # list,list -> 1차원 [2,3]
print()
print(a[[0],1:]) # -> list, 범위 -> 2차원

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[7 8 9]

[ 3  6  9 12]

[[ 3]
 [ 6]
 [ 9]
 [12]]

[[7 8 9]]

[[1 2 3]
 [4 5 6]]

[2 3]

[[2 3]]


In [38]:
#정리
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(b)
print()
print(a[1,1])    #단일값
print(a[[1],[1]])#1차원
print(a[[1],1:2])#2차원


[[1 2 3]
 [4 5 6]
 [7 8 9]]

5
[5]
[[5]]


## 조건 조회
- a[조건문] -> boolean 배열 [True, False, .... True] -> 이 중 true인 요소만 조회 

In [47]:
# 2차원 배열 만들기
score= np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])

#조건 배열
print(score%2==0)

# 짝수만 조회
print(score[score%2==0])

# 2번째 행에서 짝수만 조회
print(score[1][score[1]%2==0])

[[ True False  True False False False]
 [ True False  True False False False]]
[78 84 82 96]
[82 96]


## 배열 연산 및 집계
- 그 중 배열 집계 실습
- np.sum(), 혹은 array.sum()
    * axis = 0 : 행이 늘어나는 방향 = 열 기준 집계
    * axis = 1 : 열이 늘어나는 방향 = 행 기준 집계
    * 생략하면 : 전체 집계
- 동일한 형태로 사용 가능한 함수 : np.max(), np.min, np.mean(), np.std()

In [44]:
print(a)

# 전체 집계
print(np.sum(a))

# 열기준 집계
print(np.sum(a, axis = 0))

# 행기준 집계
print(np.sum(a, axis = 1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
78
[22 26 30]
[ 6 15 24 33]


In [45]:
# argmax - 최대값의 index

print(a)
# 전체 중에서 가장 큰 값의 인덱스
print(np.argmax(a))

# 행 방향 최대값의 인덱스
print(np.argmax(a, axis = 0))

# 열 방향 최대값의 인덱스
print(np.argmax(a, axis = 1))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
11
[3 3 3]
[2 2 2 2]
